### ISSUE TITLE
Cannot deploy through gulp-surge

### ISSUE THREAD

**Issue by limzykenneth** [surge-sh/gulp-surge#5]
Hi, I'm having problem deploying through gulp-surge, it throws the following error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/(my_project_folder)/node_modules/.bin/surge:3:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

The gulp task looks like this:
```
gulp.task("deploy:dev", ["default"], function(){
    return surge({
    	project: "./dist",         // Path to your static build directory
    	domain: "somewhere.custom.com"  // Your domain or Surge subdomain
    });
});
```

Deploying by running `surge` in the command line works as intended. Let me know if you need more info. Thanks.

**Comment by ogxn** [comment]
i suppose it's not helpful now, but if anyone needs help, it's probably missing the slash after the folder name
